spring:
  application:
    name: stationery-ecommerce

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080

jwt:
  secret: ${SECRET_KEY}
  expiration: ${EXPIRATION_TIME}
  refresh-token-duration: ${REFRESH_TOKEN_DURATION}